site_name: CheatSheet
theme:
  name: material
  features:
    - content.code.copy
    - content.action.view
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_url: https://github.com/Nonprofessional/eax-frontend-app-2

nav:
  - Home: index.md
  - Development:
      - development/index.md
      - Programming Language:
          - HTML: development/programming_language/html.md
          - CSS: development/programming_language/css.md
          - Javascript: development/programming_language/javascript.md
      - Tool:
          - Vim: development/tool/vim.md
          - Git: development/tool/git.md
  - Operation:
      - operation/index.md
      - Linux:
          - Command: operation/linux/command.md
          - Network Configure: operation/linux/network_configure.md
          - Others: operation/linux/others.md
  - Security:
      - security/index.md
